### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [josemamira/calcAzimuth#3]
There are other functions to calculate azimuth and distance.
Please clarify what the plugin is actually adding. Also, please consider adding the missing functionality to an existing plugin, rather than create a new one. This has a number of advantages, both for developers and for users.
Sorry for bothering, but we are trying hard not to duplicate functionality, so to reduce confusion for the users and administrative burden.
Thanks.

**Comment by josemamira** [comment]
I developed this complement for educational purposes, to prepare a route document with directions and distances. I wanted something simple, without more pretensions. Once finished I wanted to share it with the community.
I did not know that there were already plugins that performed this function. Now I have them installed and they are very good.
I don't care if you don't publish this add-on, and I would understand.

**Comment by pcav** [comment]
It's always a pity wasting someone's work, and we welcome anyone to come and contribute to QGIS. However, I feel responsible to keep the plugin repository as tidy as possible, avoiding duplication that creates confusion among users. According to your words, it seems that the functionality of this plugin is fully covered by other functions, right? What is your suggestion?
Thanks.

**Comment by josemamira** [comment]
Of course, this functionality is fully cover, or in others words, it's better solved with others plugins. 
Don't worry about it. You can remove this repository without any doubt (or I must to remove it from http://plugins.qgis.org/plugins ?).
I will use it in my personal Qgis installation.
Thanks for your help

**Comment by pcav** [comment]
thanks for understanding. better if you remove it.
I hope this will not discourage you from submitting your further works.
cheers.

**Comment by josemamira** [comment]
Plugin removed.
Cheers

**Comment by pcav** [comment]
Thanks a lot
